name: On Website Deploy
"on":
  push:
    # (1)
    branches:
      - "main"
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    # (2)
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🌍 Enable Web
        run: flutter config --enable-web

      - name: 📦 Get packages
        run: flutter pub get

      - name: 🏭 Build Web Application
        run: flutter build web --release
        
      - name: cd build/web
        run: cd build/web
      - name: git init
        run: git init
      - name: git config global user
        run: git config --global user.email "phamngocthachlt6c@gmail.com"
      - name: git config global name
        run: git config --global user.name "phamngocthachlt6c"
      - name: git add --all
        run: git add --all
      - name: git commit
        run: git commit -m "update"
      - name: git push
        run: git push origin

      # (3)
      - name: Make copy of artifacts
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
          bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"

      # (4)
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit the artifacts.
